### ISSUE TITLE
Cargo unload issue

### ISSUE THREAD

**Issue by guardianpwr08** [Da-Teach/Questor#6]
when finished with a mission sometimes questor gets stuck trying to unload the cargo.  If i manually close the window it will reopen and continue on.

I cannot yet find the root cause for this and it only happens maybe 25% of the time.  

edit:  I am NOT using VM ware, however i am using isboxer

**Comment by Serpentstar** [comment]
I have the exact same issue with one of my temp clients.  However,  for me, it is every time I go to open the cargo hold.  it will sit there and freeze until I close the cargo hold.  At which point it continues as it should.  I should mention this is 1 machine out of 4 and it is in a vm test machine.

**Comment by Orkanoid** [comment]
I see this is the same DirectContainer.IsReady bug I've destribed in the end of an adjacent issue (one started by me). So, Rixim, here is the answer for you: it is not fixed yet, probably.

**Comment by rixim** [comment]
can someone verify that this is fixed in the current commit?

**Comment by guardianpwr08** [comment]
so far using todays most recent build it seems fixed.

**Comment by Pluckyduck** [comment]
i unzipped the questor Mar 9th to use the xml then used this data set to update the folder,  I complied it after i put all of the contents in one folder.   This still didnt solve the cargo bug issue.
